### ISSUE TITLE
Inference results misaligned

### ISSUE THREAD

**Issue by joelbudu** [supervisely-ecosystem/yolov8#15]
Hi,
It seems the Instance segmentation inference results are misaligned, especially noticeable on rectangular images as shown in the image attached. This inference was from yolov8s-seg.

<img width="526" alt="Screenshot 2023-10-08 at 17 55 29" src="https://github.com/supervisely-ecosystem/yolov8/assets/888508/ee3ba75e-d9e5-44cd-8c2f-13daf36000c5">

**Comment by MaxTeselkin** [comment]
Hi @joelbudu ! Thanks for report, we will look into this issue. Please, next time you will face some problems / have any questions - write them in our [slack channel](https://supervisely.com/slack/) - we response there much more faster

**Comment by MaxTeselkin** [comment]
The bug was fixed in app version 1.0.33
